### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by totalspectrum** [Wuerfel21/sdldebug#1]
Not exactly a bug, but I was wondering if you mind redistribution/modification of this code, and if you don't mind, what license you'd like it under... MIT perhaps?

I was thinking it might be nice to turn this into a socket based (or maybe pipe based... sockets may be overkill) server that can accept connections from a loadp2 program. After loadp2 has run, it will optionally feed its input over to sdldebug to display on screen, filtering out any special cases (like 9p file system requests). Does this sound OK to you?

**Comment by Wuerfel21** [comment]
Yea, do whatever with this.

It currently is designed for you to pipe the data into stdin, which I guess works reasonably well, but isn't interactive.
Sockets do seem overkill and IDK how non-std pipes work cross-platform. Maybe just integrate it into loadp2? Though that'd give it a dead weight SDL2 dependency... Then again, if you never call a DLL's functions, does the DLL actually need to be there? Not sure.

Also, note that currently only the text terminal display type is implemented... though with the PNut source out, replicating the others should be easier?

**Comment by totalspectrum** [comment]
Integrating into loadp2 might be the best bet after all. Doing pipes cross-platform does seem a bit messy, and sockets would work but are a lot of overhead. loadp2 is pretty light weight, and we could make the SDL2 dependency optional at compile time for those building it from source.

Thanks,
